import './globals.css';

// ✅ Correct - layout.js
export const metadata = {
  title: 'Your App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <body >{children}</body>
    </html>
  );
}
